name: currency
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1

  # network related pub
  http: ^0.12.2

  # database related pub
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  path: ^1.7.0

  # model related pub
  built_value: ^7.1.0

  #ui related pub
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

